#include "..\..\script_component.hpp"

/*
 * Author: Moony
 * Shows the login screen and hides the desktop shell.
 */

params [["_display", displayNull, [displayNull]]];

if (isNull _display) exitWith {};

[_display, false] call FUNC(setSystemOverlay);
_display setVariable [QGVAR(startMenuOpen), false];

private _computer = _display getVariable [QGVAR(computer), objNull];
[_computer, "login"] call FUNC(setScreenState);

{
	(_display displayCtrl _x) ctrlShow false;
} forEach [
	IDC_MMC_TASKBAR,
	IDC_MMC_START_BUTTON,
	IDC_MMC_USER,
	IDC_MMC_CLOCK,
	IDC_MMC_BTN_FILES,
	IDC_MMC_BTN_MAIL,
	IDC_MMC_BTN_MESSAGES,
	IDC_MMC_BTN_NOTES,
	IDC_MMC_APP_TITLE,
	IDC_MMC_BTN_CLOSE_APP,
	IDC_MMC_APP_LIST,
	IDC_MMC_APP_BODY,
	IDC_MMC_MEDIA_BAR,
	IDC_MMC_MEDIA_PREV,
	IDC_MMC_MEDIA_PLAY,
	IDC_MMC_MEDIA_STOP,
	IDC_MMC_MEDIA_NEXT,
	IDC_MMC_MEDIA_STATUS,
	IDC_MMC_FILE_PREVIEW_IMAGE,
	IDC_MMC_START_MENU,
	IDC_MMC_FRAME_START_MENU,
	IDC_MMC_START_BOOT,
	IDC_MMC_FRAME_START_BOOT,
	IDC_MMC_START_LOGOUT,
	IDC_MMC_FRAME_START_LOGOUT,
	IDC_MMC_START_SHUTDOWN,
	IDC_MMC_FRAME_START_SHUTDOWN,
	IDC_MMC_FRAME_TASKBAR,
	IDC_MMC_FRAME_BTN_FILES,
	IDC_MMC_FRAME_BTN_MAIL,
	IDC_MMC_FRAME_BTN_MESSAGES,
	IDC_MMC_FRAME_BTN_NOTES,
	IDC_MMC_FRAME_APP_TITLE,
	IDC_MMC_FRAME_CLOSE_APP,
	IDC_MMC_FRAME_APP_LIST,
	IDC_MMC_FRAME_APP_BODY,
	IDC_MMC_FRAME_MEDIA_BAR,
	IDC_MMC_FRAME_MEDIA_PREV,
	IDC_MMC_FRAME_MEDIA_PLAY,
	IDC_MMC_FRAME_MEDIA_STOP,
	IDC_MMC_FRAME_MEDIA_NEXT,
	IDC_MMC_FRAME_FILE_PREVIEW_IMAGE,
	IDC_MMC_FRAME_START_BUTTON
];

{
	(_display displayCtrl _x) ctrlShow true;
} forEach [
	IDC_MMC_LOGIN_PANEL,
	IDC_MMC_LOGIN_TITLE,
	IDC_MMC_LOGIN_USERNAME_LABEL,
	IDC_MMC_LOGIN_USERNAME,
	IDC_MMC_LOGIN_PASSWORD_LABEL,
	IDC_MMC_LOGIN_PASSWORD,
	IDC_MMC_LOGIN_PASSWORD_VISIBLE,
	IDC_MMC_FRAME_LOGIN_PASSWORD,
	IDC_MMC_LOGIN_PASSWORD_TOGGLE,
	IDC_MMC_FRAME_LOGIN_PASSWORD_TOGGLE,
	IDC_MMC_LOGIN_BUTTON,
	IDC_MMC_FRAME_LOGIN_BUTTON,
	IDC_MMC_LOGIN_SHUTDOWN,
	IDC_MMC_FRAME_LOGIN_SHUTDOWN,
	IDC_MMC_LOGIN_ERROR,
	IDC_MMC_FRAME_LOGIN_PANEL,
	IDC_MMC_FRAME_LOGIN_USERNAME
];

(_display displayCtrl IDC_MMC_LOGIN_USERNAME) ctrlSetText "";
(_display displayCtrl IDC_MMC_LOGIN_PASSWORD) ctrlSetText "";
(_display displayCtrl IDC_MMC_LOGIN_PASSWORD_VISIBLE) ctrlSetText "";
(_display displayCtrl IDC_MMC_LOGIN_PASSWORD_VISIBLE) ctrlShow false;
(_display displayCtrl IDC_MMC_LOGIN_PASSWORD) ctrlShow true;
(_display displayCtrl IDC_MMC_LOGIN_PASSWORD_TOGGLE) ctrlSetText "Show";
_display setVariable [QGVAR(passwordVisible), false];
_display setVariable [QGVAR(loginPassword), ""];
(_display displayCtrl IDC_MMC_LOGIN_ERROR) ctrlSetStructuredText parseText "";
ctrlSetFocus (_display displayCtrl IDC_MMC_LOGIN_USERNAME);
